export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL';

export const NEXT_PAGE_REQUEST = 'NEXT_PAGE_REQUEST';
export const NEXT_PAGE_SUCCESS = 'NEXT_PAGE_SUCCESS';
export const NEXT_PAGE_FAIL = 'NEXT_PAGE_FAIL';

export const PREV_PAGE_REQUEST = 'PREV_PAGE_REQUEST';
export const PREV_PAGE_SUCCESS = 'PREV_PAGE_SUCCESS';
export const PREV_PAGE_FAIL = 'PREV_PAGE_FAIL';