export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL';

export const IMAGES_BY_CATEGORY_REQUEST = 'IMAGES_BY_CATEGORY_REQUEST';
export const IMAGES_BY_CATEGORY_SUCCESS = 'IMAGES_BY_CATEGORY_SUCCESS';
export const IMAGES_BY_CATEGORY_FAIL = 'IMAGES_BY_CATEGORY_FAIL';

export const SORT_IMAGES_REQUEST = 'SORT_IMAGES_REQUEST';
export const SORT_IMAGES_SUCCESS = 'SORT_IMAGES_SUCCESS';
export const SORT_IMAGES_FAIL = 'SORT_IMAGES_FAIL';
